# Start from a slim Python image
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Install OS dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy requirements and install them
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Download NLTK stopwords data
RUN python -m nltk.downloader -d /usr/local/nltk_data stopwords
ENV NLTK_DATA=/usr/local/nltk_data

# Copy your code into the container
COPY . .

# & Build cache
RUN python build_precompute.py || echo "⚠️ Failed to precompute (will fallback to runtime rebuild)."

# Execution
CMD ["python", "-m", "api.main"]